---
- name: Clone mastodon repo if not cloned
  git: 
    repo: "https://github.com/tootsuite/mastodon.git"
    dest: "{{ mastodon_path }}"
    update: no

- name: Check for existing .env.production
  stat:
    path: "{{ mastodon_path }}/.env.production"
  register: envfile

- block: 
  - name: Generate pgsql password
    shell: uuidgen
    register: pgpass_uuid
    when: envfile.stat.exists == False 
   
  - name: Setup docker-compose file
    template:
      src: docker-compose.yml.j2
      dest: "{{ mastodon_path }}/docker-compose.yml"

  - name: Setup partial .env.production to prepare for keys
    template:
      src: .env.production.j2
      dest: "{{ mastodon_path }}/.env.production"
  
  - name: Generate secret key
    shell: docker-compose run --rm web rake secret
    args:
      chdir: "{{ mastodon_path }}"
    register: secret_key

  - name: Generate otp key
    shell: docker-compose run --rm web rake secret
    args:
      chdir: "{{ mastodon_path }}"
    register: otp_key

  - name: Set keys
    set_fact:
      secret_key_base: "{{ secret_key.stdout }}"
      otp_secret: "{{ otp_key.stdout }}"

  - name: Setup partial .env.production to prepare for vapid keys
    template:
      src: .env.production.j2
      dest: "{{ mastodon_path }}/.env.production"
  
  - name: Generate VAPID keys
    shell: docker-compose run --rm web rake mastodon:webpush:generate_vapid_key
    args:
      chdir: "{{ mastodon_path }}"
    register: vapid_keys

  - name: Set VAPID keys
    set_fact:
      vapid_private_key: "{{ vapid_keys.stdout_lines[0] }}"
      vapid_public_key:  "{{ vapid_keys.stdout_lines[1] }}"
  
  - name: Setup .env.production
    template:
      src: .env.production.j2
      dest: "{{ mastodon_path }}/.env.production"

  - name: Do initial DB setup after .env.production is setup
    shell: docker-compose run --rm -e SAFETY_ASSURED=1 web rake db:setup
    args:
      chdir: "{{ mastodon_path }}"

  - name: Do precompiling of assets
    shell: docker-compose run --rm web rake assets:precompile
    args:
      chdir: "{{ mastodon_path }}"
  when: envfile.stat.exists == False

- name: Start mastodon
  docker_service:
    project_src: "{{ mastodon_path }}"