---
- name: Setup letsencrypt directory
  file:
    state: directory
    path: /etc/letsencrypt

- name: Run certbot for initial cert
  shell: |
    docker run \
      -v /etc/letsencrypt:/etc/letsencrypt \
      -p 80:80 \
      --rm \
      certbot/certbot \
      certonly --standalone --test-cert --register-unsafely-without-email --agree-tos -d {{ mastodon_domain }}

- name: Setup nginx directory
  file:
    state: directory
    path: /etc/nginx/conf.d

- name: Setup nginx config
  template:
    src: nginx.conf.j2
    path: /etc/nginx/conf.d/mastodon.conf

- name: Setup nginx docker container